export var PRESENTATION = {
  CELL_HIGHLIGHTS_ENABLED: true,
  CELL_FX_ENABLED: true,
  BEE_READABILITY_ENABLED: true,
  MATERIAL_RICHNESS_ENABLED: true,
  BEE_TRAILS_ENABLED: true,
  EVENT_FX_ENABLED: true
};
